### ISSUE TITLE
Simple example fails

### ISSUE THREAD

**Issue by ka3a4ok** [well-typed/binary-serialise-cbor#1]
Code below fails with message *Data.Binary.Serialise.CBOR.deserialise: failed at offset 0 : expected null*

```haskell
deserialise $ serialise (TInt 1)
```

**Comment by dcoutts** [comment]
You've been tripped up by ghci defaulting, just like `read (show 1)`

    :t deserialise $ serialise (TInt 1)
    deserialise $ serialise (TInt 1) :: Serialise a => a

So it's polymorphic in the result (just like `read . show`). If you run it, ghci defaults it to type `()`, but if you explicitly ask for it at type `Term` then it works.

**Comment by unhammer** [comment]
I ran into the same just now, and spent too long trying to debug my instance. Maybe the error message should instead say 

` DecodeFailure -> return $! SlowFail bs "expected null (or missing type annotation)"`

or something like that? And the example at the top of the Tutorial could also mention that.
