### ISSUE TITLE
Consolidate types into a single module.

### ISSUE THREAD

**Issue by thoughtpolice** [well-typed/binary-serialise-cbor#104]
In the quest to remove all boot files, because boot files are Evil, Bad, and Wrong, I think the best thing to do would simply be to move all the definitions of the major types into a single `.Types` module, much how `Class.hs` is the one place for class instances, too.

I'll be taking a whack at this later, but this is just for notice.

**Comment by bgamari** [comment]
I'm not sure we need to do this for the initial release. Let's punt on this as it's largely an internal refactoring that can be done while retaining backwards compat.

**Comment by thoughtpolice** [comment]
I'd far prefer to get it done now than later if at all possible, but it's a bit of work. I have a branch for this, so I'll try to push something soon, but I'm moving this weekend which complicates things.

**Comment by thoughtpolice** [comment]
Besides, the reasoning here is to remove everything really *before it gets worse*. Untangling it now is much better than doing it later when people want more 'things' added, surely. Plus, if we removed it *after* the initial release, we just have a bunch of dead modules for a fairly small set of users if we tried to retain compatibility. Just bumping to `0.3.0.0` would be preferable, IMO, if we did this later.

**Comment by bgamari** [comment]
Hmm, maybe I've misunderstood the intent here; Do you want to change the internal organization of the library or the user-visible export structure?

As a user, I quite like how the current module structure partitions functionality. Moving all of the types into a `.Types` module seems quite reasonable for the reasons you cite, but I'd prefer to retain the exported module structure as it looks now.

**Comment by bgamari** [comment]
In #117 we concluded that the boot files are the best approach here.
