### ISSUE TITLE
Why is Maybe different?

### ISSUE THREAD

**Issue by ghorn** [well-typed/binary-serialise-cbor#107]
The defacto standard set by `GSerialiseSum` is always a tag and an array. The handwritten types seem to keep to this.

Why is `Maybe` different? I'm having to special-case it in my generated C++ code (https://github.com/well-typed/binary-serialise-cbor/issues/89).

**Comment by thoughtpolice** [comment]
Probably just hysterical raisins, we might have missed this -- or maybe it was always mismatched. I believe `Maybe` was one of the first extant instances, so it's quite possible Duncan wrote it once and then we forgot to fix it and bring it 'in line' with the "standard encoding" later on.

This is worth fixing, of course, but I probably am not going to get to it for a few days. If you submit a patch, I'll take a look and merge, however.

**Comment by thoughtpolice** [comment]
Also: there should really be a test for this kind of thing that should stop this from happening in the future (cc #97)

**Comment by ghorn** [comment]
`Data.Tree.Tree` is also missing the tag

**Comment by ghorn** [comment]
Take a look at the patch and see if it's what you had in mind.

**Comment by dcoutts** [comment]
Sorry, only just noticed this.

This is a deliberate design choice. The rule is: types that can possibly ever change representation must have a tag, types that cannot need not have a tag and omitting it saves space.

As for uniformity: we have a number of types that the library provides instances for directly that are not the general user defined data type style. But there is a finite number of these (e.g. ByteString, Maybe).

We should clearly document this rule in the haddock docs.

**Comment by bgamari** [comment]
I've written some language into the tutorial which should address this.
