### ISSUE TITLE
Hackage link is broken

### ISSUE THREAD

**Issue by hesselink** [well-typed/binary-serialise-cbor#109]
The github summary of this repository has a link to hackage, which gives a 404. It seems the package is not on hackage at all?

**Comment by hvr** [comment]
See first paragraph of https://github.com/well-typed/binary-serialise-cbor/blob/master/README.md

...unfortunately it seems this package is subject to *the perfect is the enemy of the good* syndrome (and possibly lack of manpower to push it the [last mile to a release](https://github.com/well-typed/binary-serialise-cbor/milestone/1)?). This package has been already in development for 2 years and I've been using it in internal projects for about a year w/o any major issue.

**Comment by hesselink** [comment]
Ah, sorry, I missed that. I agree that if it's used in production, it's good to release to hackage. We have version numbers and the PVP to deal with API changes.

**Comment by joelburget** [comment]
I'm using this package for a project (https://github.com/joelburget/haskell-ipld) and am blocked from pushing *my* project to Hackage.

**Comment by thoughtpolice** [comment]
Well, to be completely frank: it's not just the perfect being the enemy of the good (I'd love, of course, to eliminate most of the major gaps before release): it's also really that none of us are being paid to work on it right now and it does its job very faithfully, so the impetus to fix the final few pieces and do release is really quite low for me, at least. (The last pushes to improve the `cbor-tool` exe from me was fallout from a recent gig, for example). And the reality is that once you release a package, people traditionally get *more* demanding, and not less.

That said, Ben has informed me the discussion on #98 has somewhat timed out with IANA/IETF, which was one of the things we were holding up for. In light of this, if we fix #17 and finally write the tutorial*, then I'd be willing to do a release and upload an initial version.

\* Which naturally means I'll be the one to write it, but I digress...

**Comment by dcoutts** [comment]
We could implement the draft RFC on the time encoding and use a private CBOR tag, and then later update to the final tag number (and still be able to read the old tag). That'd unblock that one for a release.

**Comment by bgamari** [comment]
Thanks for the prods, everyone. Seeing comments like these is good motivation to finish this up.

I've opened a few pull requests in hopes of kickstarting progress; maybe we can see a release before the week is through.

**Comment by bgamari** [comment]
I'm going to close this in favor of #115.
