### ISSUE TITLE
Exorcise `binary` dependency

### ISSUE THREAD

**Issue by thoughtpolice** [well-typed/binary-serialise-cbor#16]
The only reason the library internally depends on `binary` is for the `Decoder` type. Given that we eventually want to *replace* `binary` altogether, I'm guessing we should probably get rid of this and use our own inline version. This will force users to have a separate (or rewritten) code path, but I imagine that's an overall small cost given the large API change. I'd guess we might as well force people into it if they're going to use the new interface, then they need a new `Decoder`.

/cc @dcoutts

**Comment by dcoutts** [comment]
So I think the binary dep is fine, since we eventually want to add this as a replacement serialisation layer in the binary package.

Could think about naming again though.

**Comment by thoughtpolice** [comment]
After chatting with @dcoutts, this is basically a needlessly minute detail that is more a question of how the actual final merge with `binary` will happen. So for now, I'm closing this.

(The name of `Decoder` should be changed though, which I'll file as a separate ticket)
