### ISSUE TITLE
Consider `streaming-bytestring`?

### ISSUE THREAD

**Issue by mitchellwrosen** [well-typed/binary-serialise-cbor#21]
This is just a suggestion, and not at all an area I'm an authority on. But, I wonder what a deserialization library would look like if implemented using a [streaming-bytestring](https://hackage.haskell.org/package/streaming-bytestring), which is described in the README as "lazy ByteString done right".

Basically, it's implemented as a monad transformer, and thus `readFile` can actually perform (strict) IO, rather than be hidden under `unsafeInterleaveIO`.

**Comment by dcoutts** [comment]
As the original author of lazy bytestring, I'll have to respectfully disagree about the "lazy ByteString done right" thing. I think what's relatively clear these days is that a continuation-based implementation is the "Right Thing"tm, and then we or other libs can provide wrappers in other streaming abstractions. Starting with a continuation based impl allows that fairly easily. For example the lazy bytestring interface for binary is just a wrapper, not at all fundamental.
