### ISSUE TITLE
Rename the internal `Decoder` type

### ISSUE THREAD

**Issue by thoughtpolice** [well-typed/binary-serialise-cbor#22]
The `Decoder` type in the `.Decoding` module has an unfortunate naming conflict with the `Decoder` type from `binary`, which is mighty confusing. It's definitely confusing to me, considering they have nothing in common.

It wouldn't be a big deal if this type wasn't exposed, but it needs to be exposed for the tests.

It would probably be worth renaming this to avoid any potential confusion or whatever (hopefully with a low amount of bike shedding).

**Comment by dcoutts** [comment]
With a possible conversion to ST, we'll have to replace the Decoder from binary anyway.

**Comment by thoughtpolice** [comment]
Yes, the types will change. And in retrospect now that we'll soon be free of `binary` I find this less confusing; so I'm closing this as it should get sorted out anyway.
