### ISSUE TITLE
Support building with GHCJS

### ISSUE THREAD

**Issue by adinapoli** [well-typed/binary-serialise-cbor#3]
cc @dcoutts @kosmikus 

Hey guys!

I'm trying (perhaps with a bit of foolish, Xmas spirit!) to install IRIS' big-kitchen-sink-restful-server using GHCJS, and as it depends upon `binary-serialise-cbor` I'm hitting [an issue similar to the hashable one](https://github.com/ghcjs/ghcjs-boot/blob/master/patches/hashable.patch) which has to do with unboxed constructors:

```
    Data/Binary/Serialise/CBOR/ByteOrder.hs:202:46:
        Couldn't match expected type ‘Word#’ with actual type ‘Word64#’
        In the first argument of ‘wordToFloat64#’, namely ‘w#’
        In the first argument of ‘D#’, namely ‘(wordToFloat64# w#)’

    Data/Binary/Serialise/CBOR/ByteOrder.hs:209:40:
        Couldn't match expected type ‘Word64#’ with actual type ‘Word#’
        In the third argument of ‘writeWord64Array#’, namely ‘w#’
        In the expression: writeWord64Array# mba# 0# w# s'
```

I suspect here the problem might lie in the different word size between the native vs the JS world. Do you guys think it's possible to issue a patch [with a sane dose of CPP](https://github.com/ghcjs/ghcjs-boot/blob/master/patches/hashable.patch#L10) to make the package buildable on ghcjs? :wink:  Is even possible at all?

Thanks a ton!

A.

**Comment by thoughtpolice** [comment]
See also #20 - while this package should _mostly_ work with 32 bit (which GHCJS pretends to be), there are still some things it fails on.
