### ISSUE TITLE
Push code coverage close to 100%

### ISSUE THREAD

**Issue by thoughtpolice** [well-typed/binary-serialise-cbor#31]
As of 40909fc6e6ecf2db, on Windows 10/GHC 7.8.4 64bit:

```
$ cabal configure --enable-tests --enable-coverage
$ cabal test
$ hpc report ...
 74% expressions used (4702/6332)
 31% boolean coverage (30/95)
      27% guards (23/83), 30 always True, 1 always False, 29 unevaluated
      58% 'if' conditions (7/12), 2 always True, 1 always False, 2 unevaluated
     100% qualifiers (0/0)
 65% alternatives used (606/931)
 79% local declarations used (49/62)
 76% top-level declarations used (234/305)
```

Or:

![Screenshot](https://i.imgur.com/LdWKLwK.png)

**Comment by thoughtpolice** [comment]
As of 97ca6f4a9db197f8c3f80f921866c4cfb9894607, on Linux/amd64 with GHC 8.0.2:

```
$ cabal new-build -fhpc test:tests
$ ... run test ...
$ hpc report --include binary-serialise-cbor-0.1.1.0-inplace: tests.tix 
 73% expressions used (6178/8360)
 28% boolean coverage (31/107)
      24% guards (23/93), 39 always True, 31 unevaluated
      57% 'if' conditions (8/14), 3 always True, 3 unevaluated
     100% qualifiers (0/0)
 65% alternatives used (694/1053)
 80% local declarations used (63/78)
 84% top-level declarations used (459/544)
```
![screenshot from 2017-05-06 18-06-36](https://cloud.githubusercontent.com/assets/3416/25776557/ea154ea6-3286-11e7-8737-fa12a3f54272.png)

**Comment by bgamari** [comment]
I would say that we shouldn't hold the initial release for this.

**Comment by thoughtpolice** [comment]
Initially I had more steam on this because when I filed it I was working on the testsuite *a lot*. Honestly, I think the current results are fine; we should *aim* for 100% but probably not bend over backwards much more. Some more "negative tests" would be nice, though...
