### ISSUE TITLE
Implement a new `Get` interface

### ISSUE THREAD

**Issue by thoughtpolice** [well-typed/binary-serialise-cbor#34]
The `binary` package has two major use cases:
1. Serializing Haskell values to bytes and back, for transmission or storage.
2. Parsing arbitrary binary data in externally defined formats into Haskell values.

Currently, this library implements 1. We have not implemented 2, nor have we put much thought into a design for a faster implementation of 2 than what `binary` offers. It might look something like `.Read` in the CBOR case. Or not.

**Comment by Shimuuar** [comment]
First question is what API should be used by `Get`. I guess it's usual monadic parser combinators. 

Second question is backtracking. No backtracking means better performance. Backtracking could be useful for complicated parsers. I'm not sure what are better tradeoffs

**Comment by dcoutts** [comment]
The main difference these days between `attoparsec` and `binary` is that `binary` does not do backtracking, and this means it can release the input and be a bit faster. I think that's the same design tradeoff we would want to make.

**Comment by Shimuuar** [comment]
I just checked and `Alternative` instance of binary's `Get` does backtrack. But as I said earlier I'm not sure whether it really needed. Parsec for example does just fine with optional backtracking with `try` combinator.

**Comment by kolmodin** [comment]
`binary` does backtracking since version 0.6, released Sept 2012. I doubt it's needed for most data formats, in retrospect it should probably not have been added.
I'm not a fan of optional backtracking, it's too easy to make a mistake, the parser should always backtrack.
I also think that use of `many` is bug prone. I've used it mostly when I want to repeat as parser until the end of input, but it also stops decoding on decoder errors, which is rarely something you want when decoding binary data.

**Comment by Shimuuar** [comment]
I also want to point out that `isolate`-like combinator is invaluable in parsing existing data formats. Idiom here is size of data followed by data is ubiquitous and `isolate` make paring it very convenient.

**Comment by axman6** [comment]
Imo, it doesn't make sense to include a generic binary parser in this package - the benefits it provides are that it meets the needs of anyone needing to serialise Haskell data structures, and has the bonus of giving people a CBOR decoder for use with other systems. To me these are orthogonal issues, a serialisation library and a binary parsing library (which we already have several good alternatives, such as the current binary and attoparsec)

**Comment by bgamari** [comment]
I tend to agree that this package should stick to what it does well; `binary` is already a perfectly fine tool for dealing with externally-specified binary formats.
