### ISSUE TITLE
Look into Packman benchmarks

### ISSUE THREAD

**Issue by thoughtpolice** [well-typed/binary-serialise-cbor#43]
Another competitor has appeared!

https://github.com/jberthold/binary-serialise-cbor/commit/ba522df799071e02cb1639c4d6ac4d8b334817cd

(more along the lines of `read/show`, but intriguing nonetheless!)

**Comment by dcoutts** [comment]
See also https://hackage.haskell.org/package/store which is very low level. We can't expect cbor to be faster, but it provides a stretch goal. Plus, we can employ a few cunning tricks like parallel arrays.

**Comment by thoughtpolice** [comment]
Dropping this for now; we do benchmark again store, but frankly adding 9 gazillion frameworks to test against probably isn't the best use of time considering it makes everything slower (and the benchmarks are already ridiculous to compile anyway).
