### ISSUE TITLE
Serialise vs Serialize

### ISSUE THREAD

**Issue by mihaimaruseac** [well-typed/binary-serialise-cbor#48]
As discussed at the Haskell Boston meetup, the code contains both spellings of the word and there needs to be an issue and a pull request to fix that.

**Comment by arianvp** [comment]
I keep misspelling it during coding.   Can't you use type synonyms for   typeclasses as well?

`type Serialize = Serialise`

**Comment by mitchellwrosen** [comment]
I believe you can with `-XConstraintKinds`

**Comment by thoughtpolice** [comment]
Maybe we can have the build bots flag an error when you spell it with a 'z'. Perhaps we could have an ASCII dragon with a teacup who gets angry and the build fails.

**Comment by thoughtpolice** [comment]
(FWIW, this is only a half serious suggestion. I'd be maybe OK with a type alias, but considering we haven't even released this library yet it'd be nicer if it was consistent!)

@dcoutts might have some opinions, too.

**Comment by dcoutts** [comment]
So I'm British spelling zealot, so I vote for consistently using serialise :-)

**Comment by ghorn** [comment]
I have no problem using a British-flavored library, especially if it makes Duncan happy

**Comment by dcoutts** [comment]
I think you're all lovely for pandering to me (*sniff, holds back tears*) and only slightly silly.

@thoughtpolice clearly we should add the British tea dragon to hslint.

**Comment by ghorn** [comment]
I would just like you to know that I started to adopt this spelling into my work codebase but only made it 80% of the way, and now I'm pretty sure I'm broken forever. I don't actually mind though.
