### ISSUE TITLE
Skip tag for single-constructor data types?

### ISSUE THREAD

**Issue by edsko** [well-typed/binary-serialise-cbor#73]
The generic serialisation and deserialisation has a special case for single-constructor-single-field data types (instance for `GSerialiseEncode (K1 i a)`), but does not introduce a special case for single-constructor-multiple-fields (instance for `GSerialiseEncode (f :+: g)`). This means if you have something like

``` haskell
data Foo = Foo {
    some   :: ..
  , record :: ..
  , type   :: ..
  , with   :: ..
  , lots   :: ..
  , of     :: ..
  , fields :: ..
  }
```

and we serialize a bunch of these, every one will have an unnecessary extra tag field.

**Comment by edsko** [comment]
Although I suppose maybe this is by design, so that if later constructors are added things don't break? If so, perhaps some convenience function to make it easier to define such instances manually might be helpful (if the programmer knows there will not be more constructors). The library provides instances for tuples, but only up to length 7 (I'm guessing the same function that I'm proposing here could also be useful to define those tuple instances).

**Comment by dcoutts** [comment]
This is by design. Actually I'm concerned that the single-constructor-single-field data types don't have a tag. The tags are not just for multiple constructors but to allow for migrations when you change the constructor in future.

**Comment by dcoutts** [comment]
The single-constructor-single-field special case should be eliminated.

**Comment by bgamari** [comment]
Indeed the single-field case was eliminated in db52a1168c15d84a1ee5543e425ad21eaea3ffb8.
