### ISSUE TITLE
Confusing error message in generic Serialise instance for sums

### ISSUE THREAD

**Issue by edsko** [well-typed/binary-serialise-cbor#74]
We have

``` haskell
      when (fromIntegral n /= nF + 1) $
        fail $ "Wrong number of fields: expected="++show nF++" got="++show n
```

leading to error messages such as

```
Wrong number of fields: expected=14 got=14
```

**Comment by thoughtpolice** [comment]
i am assigning this as 'rocket science' difficulty. do not attempt unless you have 12 Haskell PhDs!

**Comment by dcoutts** [comment]
Hah. Though I'm not quite sure why it needs 12 PhDs...

**Comment by thoughtpolice** [comment]
> Hah. Though I'm not quite sure why it needs 12 PhDs...

<[insert complex, numerological, completely conspiratorial explanation of why 12 is the exact number needed](http://timecube.2enp.com/)>

**Comment by ghorn** [comment]
I have a humble attempt at a fix in https://github.com/well-typed/binary-serialise-cbor/pull/79
