### ISSUE TITLE
Bug in implementation of `decode` for Either

### ISSUE THREAD

**Issue by axman6** [well-typed/binary-serialise-cbor#8]
At https://github.com/well-typed/binary-serialise-cbor/blob/master/Data/Binary/Serialise/CBOR/Class.hs#L202 the recent PR to add more strictness (#5) failed to add in the `Left` and `Right` constructors when decoding `Either`s. I haven't tested it, but I expect that at best this will always cause decoding to fail, and at worse could cause an infinite loop, but that's probably unlikely (the instance for `Either` is relying on its own instance recursively, the x's both have type `Either a b`)

**Comment by adamgundry** [comment]
Well spotted, thanks!
