### ISSUE TITLE
Generic default instances appear to be not significantly faster than cereal

### ISSUE THREAD

**Issue by jberryman** [well-typed/binary-serialise-cbor#86]
I initially had several `UTCTime`s and ran into #51, observing cbor 10x slower than cereal. After removing them from the test case, the performance of this package and cereal appear about the same (~17 us for a roundtrip, with `cereal` being faster at deserializing and this package faster at serializing).

Here's my test case (which is a cleaned up version of one of the ADTs we serialize in our app, with `UTCTime`s replaced by `Text`).

```
instance CBOR.Serialise PPTS
instance CBOR.Serialise AMs
instance CBOR.Serialise AM
instance CBOR.Serialise SM
instance CBOR.Serialise CH
instance CBOR.Serialise RMs
instance CBOR.Serialise RM
instance CBOR.Serialise Im
instance CBOR.Serialise VDs

newtype SM = SM { _sm :: (HS.HashSet Text) }
  deriving (NFData, Eq, Show, Generic)

newtype CH = CH { _ch :: Maybe Text }
  deriving (NFData, Eq, Show, Generic)

newtype RMs = RMs { _rm :: [RM] }
  deriving (NFData, Eq, Show, Generic)

data Im = Im (HM.HashMap Text Text) VDs
    deriving (NFData, Eq, Show, Generic)

newtype VDs = VDs { _vlsL :: HM.HashMap Text (Text,Text) }
    deriving (NFData, Eq, Show, Generic)

data RM = RM Text [Text] [Text] Text
    deriving (NFData, Show, Eq, Generic)

data PPTS = PPTS SM CH Im RMs AMs (Maybe Text)
  deriving (NFData, Eq, Show, Typeable, Generic)

data AM = AM Text Text [Text] Text Int
   deriving (NFData, Show, Eq, Generic)

newtype AMs = AMs [AM] 
  deriving (NFData, Eq, Show, Generic)

-- make this UTCTime for a real test case:
fakeTime = "asdf-2345234-sasdf UTC"
ppts = 
 PPTS 
  (SM (HS.fromList ["asdf", "2345234 23452345", "asdfasdf", "2345"]))
  (CH $ Just "he dfdfdfdf dfdfddf llp")
  (Im (HM.fromList [("sasd 5555555987","dff f"),("sasd 5555555987","dff f"),("sasd 5555555987","dff f"),("sasd 5555555987","dff f"),("sasd 5555555987","dff f"),("sasd 5555555987","dff f"),("sasd 5555555987","dff f"),("sasd 5555555987","dff f"),("sasd 5555555987","dff f"),("sasd 5555555987","dff f"),("sasd 5555555987","dff f")]) (VDs (HM.fromList [ ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")), ("sasd 55 344455555987",("dfffffffffff f","asdfasdfdddf")) ])))
  (RMs [
     RM (fakeTime) ["hello", "world"] ["hedddddddddddddddddddddddddddlp"] "somenaml"
   , RM (fakeTime) ["asdfasdfhello", "world"] ["hedddddddddddddddddddddddddddlp"] "somenaml"
   , RM (fakeTime) ["hello", "wasdfdforld"] ["hedddaddfdfdddddddddddddddddddddddddlp"] "somenaml"
   , RM (fakeTime) ["he444444444444444asdkhjasdfllo", "world"] ["hedddddddddddddddaddfdfdddddddddddddlp"] "somenaml"
    ])
  (AMs [
     AM (fakeTime) "fffffffffffffffffffffffff" ["s","adfasdfasdfasdf"] "hellpasd akjha" 9874587484845
   , AM (fakeTime) "fffffffffffffffffffffffff" ["s","adfasdfasdfasdf"] "hellpasd akjha" 9874345484845
   , AM (fakeTime) "fffffff     asdf ffffffffffffffffff" [] "hellpasd akjha" 3434345484845
   ])
  Nothing

-- and instance for `cereal`:

instance C.Serialize PPTS
instance C.Serialize AMs
instance C.Serialize AM
instance C.Serialize SM
instance C.Serialize CH
instance C.Serialize RMs
instance C.Serialize RM
instance C.Serialize Im
instance C.Serialize VDs
instance (Eq a, Hashable a, C.Serialize a) => C.Serialize (HS.HashSet a) where
  put = C.put . HS.toList
  get = HS.fromList <$> C.get
instance (Eq a, Hashable a, C.Serialize a, C.Serialize b) => C.Serialize (HM.HashMap a b) where
  put = C.put . HM.toList
  get = HM.fromList <$> C.get

instance C.Serialize Text where
  put = C.put . T.encodeUtf8
  get = T.decodeUtf8 <$> C.get

```

If I change the `HashMap` and `HashSet` to lists in the usual way performance looks like (for serializatioon + deserialization):

```
cereal: 23.15 μs +  19.54 μs
cbor:    17.17 μs + 19.30 μs
```

That's as far as I could justify tweaking the type. We're struggling with serialization performance but don't have the time to write and test definitions like these by hand: https://github.com/well-typed/binary-serialise-cbor/blob/master/bench/versus/Macro/CBOR.hs

Let me know if I'm missing something obvious, but otherwise I hope the above is a useful test case. Thanks for your work on this package!

**Comment by thoughtpolice** [comment]
What sort of performance are you seeing in general? Can you give an expectation of the benchmark and the data size, application characteristics, etc so we could try to replicate any possible problems? What leads you to believe the `Generic` instances are at play here? Does this exact example get faster if you write them out manually? It's hard to directly evaluate without answering all these.

Briefly: at a glance, it's not really surprising that `cereal` does OK in micro benchmarks vs `cbor`. In fact, our own benchmarks should basically say as much - they do very well when serializing very tiny things in very simple examples. There's not much code to 'blind' the optimizer with a small set of types and values, so it will normally do OK inlining and unboxing away the intermediate states. Indeed, with a closed world single-module where all instances live there, and all data is static like your example, GHC will probably do very well. But the problem is both `cereal` and `binary` fundamentally is that they generate lots of code for creating an instance, and this really can't be avoided, and incurs fundamental overheads (fragile global optimization to optimize away/unbox intermediates, the costs of allocating continuations, etc. If you change a type and the optimizer suddenly starts failing because something became 'too big' or somesuch, you'll be annoyed and sad).

If you have like, a really large value, I'd expect cbor to be a lot better (as an example, try the `vs-other-libs` benchmark, the `Macro.hs` link you included is part of it), and `cbor` should fair much better.

**Comment by thoughtpolice** [comment]
Just a thought: if you replace `Macro.hs` in `vs-other-libs` with a version that has `Generic`-derived `Serialise` instances, perhaps that would lend evidence to `Generic` being the culprit if there was a large discrepancy?

**Comment by jberryman** [comment]
> Just a thought: if you replace Macro.hs in vs-other-libs with a version that has Generic-derived Serialise instances

Yeah that would be a good idea for comparison. This ticket was more like "here's my realistic example where I found cbor to be not significantly faster than cereal. I happen to (need to) be using Generic-derived instances so I mentioned it in the title.

I'm just going to close this. I'll try to contribute some benchmarks as PRs if I get to pursue this. Thanks for the reply.
