### ISSUE TITLE
Stricter Lists and Maps in Term

### ISSUE THREAD

**Issue by andrewthad** [well-typed/binary-serialise-cbor#91]
In the [definition of `Term`](https://github.com/well-typed/binary-serialise-cbor/blob/59e39abb14c4f61ca46f42681df7dc266d62e96a/Data/Binary/Serialise/CBOR/Term.hs#L72-L75), we have definite and indefinite variants of several things:

    data Term
      = TInt     {-# UNPACK #-} !Int
      | TInteger                !Integer
      | TBytes                  !BS.ByteString
      | TBytesI                 !LBS.ByteString
      | TString                 !T.Text
      | TStringI                !LT.Text
      | TList                   ![Term]
      | TListI                  ![Term]
      | TMap                    ![(Term, Term)]
      | TMapI                   ![(Term, Term)]
      ...

I mostly like this design (although it may be nice to have a variant of `Term` that can actually stream the indefinite structures when decoding, but that's a digression). My request is that `TList` and `TMap` be changed to take `Vector`s instead of lists. This is more consistent with the way that `TBytes` and `TString` are defined, and the encoding/decoding for these should be a little faster.

**Comment by dcoutts** [comment]
@andrewthad Hmm, interesting. What application do you have that uses Term where performance is important? I'd assumed that Term was primarily for testing/debugging/understanding and not for serious use.

**Comment by andrewthad** [comment]
I do not have any applications in mind. You're right though, the importance of `Term` shouldn't usually be important. I'll reopen this if I ever find myself doing a ton of inspecting arbitrary `Term`s (which seems unlikely).
